pinterest/thriftcheck

- README.md
- checks/includes.go
- cmd/main.go
- linter.go
This better matches the name of the matching node ('include'), which is
consistent with the other checks' names. Also, we'll likely have other
include-based checks, so using the dot-based notation will make that
more obvious. It will also avoid any confusion with the 'nolint'
syntax's hierarchical matching.
> Rename 'includes' to 'include.exists'

- README.md
- checks/includes.go
- checks/includes_test.go
- checks/namespaces.go
- cmd/main.go
- cmd/thriftcheck.example.toml
This check restricts some files from being imported by other files using
a map of regular expressions: the key matches the including filename and
the value matches the included filename. When both match, the `include`
is flagged as "restricted" and an error is reported.
> Add a new 'include.restricted' check

- README.md
- checks/includes.go
- checks/includes_test.go
- cmd/thriftcheck.example.toml
The previous regular expression syntax was a bit heavy for the left-hand
side of this table. We can instead use the simpler file name pattern
syntax.
I'm keeping the richer regular expression syntax for the right-hand side
because it gives us a nice way to match multiple unrelated files using
groups. The alternative would be to express the configuration block as a
list of (pattern, pattern) pairs (rather than a map), which would allow
repeated left-hand side values, but that doesn't feel like the right
trade-off.
> Use filepath.Match() to match keys in include.restricted

- checks/checks_test.go
- checks/enums_test.go
- checks/fields_test.go
- checks/includes_test.go
- checks/maps_test.go
- checks/namespaces_test.go
- checks/sets_test.go
All checks tests now use a common Test struct and run their tests via a
RunTests() helper function.
> Standardize the checks unit test pattern

- go.mod
- go.sum
- linter.go
- linter_test.go
Previously, parse errors were written using an ad hoc error format. Now
that thriftrw-go can returns a structured idl.ParseError, we can unpack
that and report a complete error message.
> Report parse errors are first-class error messages

- linter.go
- linter_test.go
Now that thriftrw supports line numbers in parse errors, we can include
that information as part of our own reports.
> Report line numbers for parse errors

- ast.go
- check.go
- go.mod
- go.sum
- linter.go
- linter_test.go
- message.go
- message_test.go
- parse.go
This switches to thriftrw's new Config-based parsing system, which
provides an idl.Info structure containing supplemental node positions
for AST types that don't support ast.LineNumber() natively.
> Use parsed idl.Info to determine node positions

- README.md
- checks/ints.go
- checks/ints_test.go
- cmd/main.go
This check warns when an integer constant exceeds the 32-bit number
range. Some languages (e.g. JavaScript) don't support 64-bit integers.
> Add a new int.64bit check

- go.mod
- go.sum
- linter_test.go
- message.go
These are currently only available for parse errors, but wider
node-level support will come next.
We continue to display 1 (instead of 0) in our message output when
column information isn't available.
> Support ast.Position column numbers

- checks/includes.go
- checks/includes_test.go
- go.mod
- go.sum
filepath.Match() is aware of directory separators. This makes sense for
shell-style matching but isn't as convenient working with arbitrary file
paths because the directory hierarchy needs to be expressed in the
pattern.
fnmatch(3) offers a FNM_NOESCAPE flag that avoid that problem. When set,
directory separators are treated like normal characters. This is more
intuitive for our use case (and matches Python's fnmatch.fnmatch()).
We can use github.com/danwakefield/fnmatch for a Go implementation of
the fnmatch(3) matching rules.
> Use fnmatch()-style file path matching

- README.md
- check.go
- cmd/main.go
- linter.go
This gives us a quick way to see which checks are enabled or disabled
based on the current configuration.
Also, we can pass the Checks slice around by value nearly everywhere.
This is no less efficient in Go. We still use pointers to track
overrides, however.
> List enabled/disabled status alongside check names

- README.md
- ast.go
- ast_test.go
- linter.go
- nolint.go
- nolint_test.go
This mimics the annotation-based syntax:
nolint = ""         @nolint
nolint = "a,b"      @nolint(a,b)
The annotation syntax is preferred, but the documentation block syntax
is useful for those few cases where the target node doesn't support
Thrift annotations (such as `const` declarations).
Closed #13
> Support documented-based @nolint directives

- README.md
- ast.go
- checks/names.go
- checks/names_test.go
- cmd/example.toml
- cmd/main.go
This checks allows you to extend the default list of reserved keywords
with additional names.
Fixed #21
> Add a new 'names.reserved' check

- check.go
- checks/includes.go
- parse.go
We were previously using the including file's name, which I mistakenly
thought was the `thrift` compiler's behavior. We instead need to add the
current directory as the first search path to match `thrift`.
This change also adds support for absolute paths and makes consistent
use of the `path/filepath` package for better cross-platform support.
> Use current directory to resolve includes

- .golangci.yml
- message.go
In particular, we now check that all source files include our Apache 2.0
license header block.
> Enable a few more linters

- README.md
- checks/fields.go
- checks/fields_test.go
- cmd/main.go
`field.optional` warns if a field isn't declared as "optional", which is
considered a best practice.
`field.requireness` warns if a field isn't explicit declared as
"required" or "optional".
> Add 'field.optional' and 'field.requiredness' checks

- ast.go
- ast_test.go
- go.mod
- go.sum
- nolint.go
This functionality is now provided by thriftrw so we don't need to
provide our own reflection-based implementation.
> Switch to ast.Annotations()

- README.md
- checks/enums_test.go
- checks/fields_test.go
- checks/includes_test.go
- checks/ints_test.go
- checks/maps_test.go
- checks/names_test.go
- checks/namespaces_test.go
- checks/sets_test.go
- linter_test.go
- message.go
- message_test.go
It's more common for tools like this to include a space before the
"severity" prefix. By adopting this GCC-style format, more tools will be
able to parse our output by default without additional configuration.
> More closely match GCC-style error format

- go.mod
- go.sum
- https://github.com/thriftrw/thriftrw-go/releases/tag/v1.29.0
- https://github.com/thriftrw/thriftrw-go/releases/tag/v1.29.1
- https://github.com/thriftrw/thriftrw-go/releases/tag/v1.29.2
> Upgrade to thriftrw v1.29.2

- .pre-commit-hooks.yaml
- README.md
pre-commit (https://pre-commit.com/) is a framework for managing and
maintaining multi-language pre-commit hooks. It allows repositories to
export "hooks" that define individual linters; source repositories can
use these exported hooks as part of their own pre-commit configuration.
By providing .pre-commit-hooks.yaml, we're able to participate in this
system, making it easy for people to use thriftcheck with pre-commit.
> Add pre-commit hooks support

- .github/workflows/ci.yml
Test on both 1.17 and 1.18, but lint only on 1.18.
> Add Go version 1.18 to the testing matrix

- ast.go
We only want to report the more generic "could not be resolved" error
from here rather than a possible "missing 'import'" error. The latter
can occur when attempting to speculatively resolve an "Enum.Value" name.
> Improve ResolveConstant error value

- README.md
- checks/fields.go
- checks/fields_test.go
- cmd/main.go
This check reports an error if a field's ID is zero, which is generally
unsupported by the Apache Thrift compiler. This is distinct from the
`field.id.negative` check given the existence of the `--allow-neg-keys`
Apache Thrift compiler option.
> Add a 'field.id.zero' check

- README.md
- checks/fields.go
- checks/fields_test.go
Auto-assigned field IDs start at zero and then go negative. If auto-
assigned fields are intentionally used (i.e. no `field.id.missing`
check), then it's not helpful to report additional errors about the
range of the auto-assigned values.
These checks now only report errors for explicitly assigned field IDs.
> Only apply 'field.id.{negative,zero}' to explicit field IDs

- .github/workflows/ci.yml
This ensures that go.mod is up-to-date and doesn't contain any
unnecessary entries.
> Run `go mod tidy`

- .gitignore
- README.md
- checks/fields.go
- checks/fields_test.go
- cmd/main.go
As discussed in [this issue](https://github.com/pinterest/thriftcheck/issues/60) before, and based on the current implementation of `thriftrw-go`, I added a simple check for comments. This will be helpful for some code quality checks.
By the way, I added two folders to .gitignore for the purpose of compiling and including test files later.
Closes #60
> 🚩 add struct field comment check

- .github/workflows/ci.yml
This option was removed in golangci-lint-action v3 in favor of explicitly using actions/setup-go.
> Remove 'skip-go-installation'

- README.md
- cmd/main.go
Otherwise, we would attempt to parse non-Thrift nested within the directory hierarchy.
> Only recursively expand .thrift files

- linter.go
- linter_test.go
- parse.go
As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code.
> Replace deprecated ioutil usage with equivalents

- cmd/main.go
This will cause configuration parsing to fail with an error when extra (unknown) keys are present in the configuration file.
> Enable strict configuration parsing

- .github/workflows/ci.yml
- .github/workflows/release.yml
Also, use Go 1.22 for the lint and release pipelines.
> Add Go 1.22 to the testing matrix

- checks/maps.go
- types.go
- types_test.go
Now that we only need the exported ThriftType in the public interface,
we can simplify a few things about the implementation:
- Implement Stringer for ThriftType
- Only store the type's name within ThriftType
- Convert typeMatcher an internal function type
> Simplify the type matching implementation

- linter.go
- parse.go
This was an oversight that caused file descriptor leaks. In practice, these were cleaned up when our short-lived program exited, but this approach is now more efficient and correct.
> Close() opened files after reading

- .github/workflows/ci.yml
- go.mod
- types.go
Go 1.23 was released about a year ago, and this version lets us use the iter, slices, and maps packages.
> Use Go 1.23 as our minimum language version

- README.md
- checks/maps.go
- checks/maps_test.go
- cmd/example.toml
- cmd/main.go
- types.go
- types_test.go
This PR adds a new configurable check to allow/disallow specific types from being used as `map<>` keys.
The new check will be named `map.key.type`. That name was already taken by a different check, which will be renamed to `map.key.type.primitve`.
We wanted to add a check to only allow integers and enums as map keys. If we only added it in the 'allowed' flavor, it'd be strange, considering we already have the `map.value.restricted` check which disallows types. Sometimes it makes more sense to specify what to allow, and sometimes it makes more sense to specify what to disallow. So we're adding both options.
As future work we can update the `map.value.restricted` check to also cover both cases, to be consistent with this one. Also the `types.disallowed` check.
> Add a check to allow/disallow map key types

- README.md
- check.go
- check_test.go
- checks/checks_test.go
- checks/maps.go
- checks/maps_test.go
- checks/sets.go
- checks/sets_test.go
- checks/types.go
- checks/types_test.go
- cmd/example.toml
- cmd/main.go
All type-based checks (maps, sets, and "global") now use consistent
logic and configuration keys.
They can be configured with "allowedTypes" and "disallowedTypes" lists.
If the type appears in "disallowedTypes", an error is reported. If the
list "allowedTypes" is not empty, then the type must appear in it, or an
error is reported.
This is a breaking change for some existing checks, but it gives us a
lot more flexibility after a one-time configuration update, so lets roll
with it.
> Make all types-based checks consistent

- README.md
- cmd/example.toml
- types.go
- types_test.go
This pseudo-type name matches any base type. It's a useful shorthand for a common use case.
Also, refer to these types collectively as "base types" rather than "primitives", which is more inline with Thrift's terminology. Similarly, use the term "definitions" to group enumerations and structures.
> Add a "base" type name

- types.go
- types_test.go
This gives us complete test coverage across all of the type matchers for both the positive and negative cases (i.e. a matcher should only match its target type and no others).
This doesn't yet cover the type resolution (ast.TypeReference) code paths. That will come next.
> Revise the type matching tests
